### ISSUE TITLE
Incorrect slashes generated when targetting nodejs on a windows machine

### ISSUE THREAD

**Issue by kewne** [bhauman/figwheel-main#136]
This seems to be the same as #19 but for nodejs.

This is what I get in `nodejs.log` when running `lein fig:build` with a project generated from the template and setting  `:target :nodejs`:
```
Debugger listening on ws://127.0.0.1:9229/a5c6c02e-bb6f-4703-b0c3-0f11f1dd15d1
For help see https://nodejs.org/en/docs/inspector
Error: Cannot find module 'C:\Users\joao.cabrita\projects\clojurescript-function-vc\resources
odedev\goog\bootstrap\nodejs.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\joao.cabrita\projects\clojurescript-function-vc\resources\node\dev\dev-main.js:19:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

Lines 19 and 20 of my `dev-main.js` have the following:
```
require(path.join(path.resolve("."),"resources\node\dev","goog","bootstrap","nodejs.js"));
require(path.join(path.resolve("."),"resources\node\dev","cljs_deps.js"));
```

For some reason, `resources/node/dev` is treated as a single part and has windows path separators, causing the module load error (`\n` is converted to newline and `\d` is converted to d).

**Comment by bhauman** [comment]
Hmmm what's your configuration here? and what version of figwheel-main are you using?  

This shouldn't be problem unless you are setting your `:asset-path` manually, or are using an old version of figwheel-main.

**Comment by kewne** [comment]
Here's my configuration:
project.clj:
```clojure
(defproject cljs-cf-vc "0.1.0-SNAPSHOT"
  :description "FIXME: write this!"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}

  :min-lein-version "2.7.1"

  :dependencies [[org.clojure/clojure "1.9.0"]
                 [org.clojure/clojurescript "1.10.339"]]

  :source-paths ["src"]

  :aliases {"fig"       ["run" "-m" "figwheel.main"]
            "fig:build" ["run" "-m" "figwheel.main" "-b" "dev" "-r"]
            "fig:min"   ["run" "-m" "figwheel.main" "-O" "advanced" "-bo" "dev"]
            "fig:test"  ["run" "-m" "figwheel.main" "-co" "test.cljs.edn" "-m" cljs-cf-vc.test-runner]}

  :profiles {:dev {:dependencies [[com.bhauman/figwheel-main "0.2.0"]]
                   }})
```

dev.cljs.edn:
```clojure
^{:watch-dirs ["test" "src"]
  :css-dirs ["resources/public/css"]
  :auto-testing true}
{:main cljs-cf-vc.core
 :target :nodejs}
```

figwheel-main.edn:
```clojure
{
 :target-dir "resources"
}
```

**Comment by bhauman** [comment]
OK cool thanks I'll take a closer look.

**Comment by kewne** [comment]
Ah, forgot to mention that the same configuration, when running on linux (ubuntu on windows, at least), works fine.

Thanks for taking the time to look into this!
