### ISSUE TITLE
Webpack failure on packaging with fig:min

### ISSUE THREAD

**Issue by danielmarreirosdeoliveira** [bhauman/figwheel-main#286]
Hello,
In this branch https://github.com/danielmarreirosdeoliveira/fullstack-clj/tree/packaging-issue of a fullstack starter app I have the following issue. Following instructions from https://figwheel.org/docs/npm.html I added `:auto-bundle :webpack` in `dev.cljs.edn` added the `npm` dependency for `moment`. I also adjusted my `index.html` to include `<script src="cljs-out/dev/main_bundle.js" type="text/javascript"></script>` instead of `<script src="cljs-out/dev-main.js" type="text/javascript"></script>`. In `src/cljs/ui_main.js` I require `[moment :as mom]`. This all works fine with `fig:build`. When I try to `fig:min`, however, in preparation for deployment, I get the following error:

```
2021-04-05 17:01:04.310:INFO::main: Logging initialized @2282ms to org.eclipse.jetty.util.log.StdErrLog
[Figwheel] Validating figwheel-main.edn
[Figwheel] figwheel-main.edn is valid \(ツ)/
[Figwheel] Compiling build dev to "resources/public/cljs-out/dev/main.js"
[Figwheel] Successfully compiled build dev to "resources/public/cljs-out/dev/main.js" in 9.826 seconds.
[Figwheel] Bundling: npx webpack --mode=production ./resources/public/cljs-out/dev/main.js --output-path ./resources/public/cljs-out/dev --output-filename main_bundle.js
[Figwheel:SEVERE] Bundling command failed
assets by status 702 KiB [cached] 1 asset
runtime modules 211 bytes 2 modules
modules by path ./node_modules/moment/locale/*.js 499 KiB 135 modules
modules by path ./resources/public/cljs-out/dev/ 422 KiB
  ./resources/public/cljs-out/dev/main.js 422 KiB [built] [code generated]
  ./resources/public/cljs-out/dev/ sync 160 bytes [built] [code generated]
./node_modules/moment/moment.js 170 KiB [built] [code generated]
./node_modules/moment/locale/ sync ^\.\/.*$ 3.21 KiB [optional] [built] [code generated]

WARNING in ./resources/public/cljs-out/dev/main.js 772:177-179
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./resources/public/cljs-out/dev/main.js 772:182-184
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./resources/public/cljs-out/dev/main.js 772:205-207
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

3 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

ERROR in ./resources/public/cljs-out/dev/main.js 57:95-111
Module not found: Error: Can't resolve 'react' in '/home/daniel/Workspace/Checkouts/fullstack-clj/resources/public/cljs-out/dev'
resolve 'react' in '/home/daniel/Workspace/Checkouts/fullstack-clj/resources/public/cljs-out/dev'
  Parsed request is a module
  using description file: /home/daniel/Workspace/Checkouts/fullstack-clj/package.json (relative path: ./resources/public/cljs-out/dev)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/daniel/Workspace/Checkouts/fullstack-clj/resources/public/cljs-out/dev/node_modules doesn't exist or is not a directory
      /home/daniel/Workspace/Checkouts/fullstack-clj/resources/public/cljs-out/node_modules doesn't exist or is not a directory
      /home/daniel/Workspace/Checkouts/fullstack-clj/resources/public/node_modules doesn't exist or is not a directory
      /home/daniel/Workspace/Checkouts/fullstack-clj/resources/node_modules doesn't exist or is not a directory
      looking for modules in /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules
        single file module
          using description file: /home/daniel/Workspace/Checkouts/fullstack-clj/package.json (relative path: ./node_modules/react)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules/react doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules/react.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules/react.json doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules/react.wasm doesn't exist
        /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules/react doesn't exist
      /home/daniel/Workspace/Checkouts/node_modules doesn't exist or is not a directory
      /home/daniel/Workspace/node_modules doesn't exist or is not a directory
      /home/daniel/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory

webpack 5.30.0 compiled with 1 error and 3 warnings in 6295 ms

Exception in thread "main" Syntax error compiling at (/tmp/form-init15416168890662789767.clj:1:74).
Bundling command failed
assets by status 702 KiB [cached] 1 asset
runtime modules 211 bytes 2 modules
modules by path ./node_modules/moment/locale/*.js 499 KiB 135 modules
modules by path ./resources/public/cljs-out/dev/ 422 KiB
  ./resources/public/cljs-out/dev/main.js 422 KiB [built] [code generated]
  ./resources/public/cljs-out/dev/ sync 160 bytes [built] [code generated]
./node_modules/moment/moment.js 170 KiB [built] [code generated]
./node_modules/moment/locale/ sync ^\.\/.*$ 3.21 KiB [optional] [built] [code generated]

WARNING in ./resources/public/cljs-out/dev/main.js 772:177-179
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./resources/public/cljs-out/dev/main.js 772:182-184
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./resources/public/cljs-out/dev/main.js 772:205-207
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

3 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

ERROR in ./resources/public/cljs-out/dev/main.js 57:95-111
Module not found: Error: Can't resolve 'react' in '/home/daniel/Workspace/Checkouts/fullstack-clj/resources/public/cljs-out/dev'
resolve 'react' in '/home/daniel/Workspace/Checkouts/fullstack-clj/resources/public/cljs-out/dev'
  Parsed request is a module
  using description file: /home/daniel/Workspace/Checkouts/fullstack-clj/package.json (relative path: ./resources/public/cljs-out/dev)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/daniel/Workspace/Checkouts/fullstack-clj/resources/public/cljs-out/dev/node_modules doesn't exist or is not a directory
      /home/daniel/Workspace/Checkouts/fullstack-clj/resources/public/cljs-out/node_modules doesn't exist or is not a directory
      /home/daniel/Workspace/Checkouts/fullstack-clj/resources/public/node_modules doesn't exist or is not a directory
      /home/daniel/Workspace/Checkouts/fullstack-clj/resources/node_modules doesn't exist or is not a directory
      looking for modules in /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules
        single file module
          using description file: /home/daniel/Workspace/Checkouts/fullstack-clj/package.json (relative path: ./node_modules/react)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules/react doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules/react.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules/react.json doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules/react.wasm doesn't exist
        /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules/react doesn't exist
      /home/daniel/Workspace/Checkouts/node_modules doesn't exist or is not a directory
      /home/daniel/Workspace/node_modules doesn't exist or is not a directory
      /home/daniel/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory

webpack 5.30.0 compiled with 1 error and 3 warnings in 6295 ms

	at clojure.lang.Compiler.load(Compiler.java:7647)
	at clojure.lang.Compiler.loadFile(Compiler.java:7573)
	at clojure.main$load_script.invokeStatic(main.clj:452)
	at clojure.main$init_opt.invokeStatic(main.clj:454)
	at clojure.main$init_opt.invoke(main.clj:454)
	at clojure.main$initialize.invokeStatic(main.clj:485)
	at clojure.main$null_opt.invokeStatic(main.clj:519)
	at clojure.main$null_opt.invoke(main.clj:516)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: Bundling command failed
assets by status 702 KiB [cached] 1 asset
runtime modules 211 bytes 2 modules
modules by path ./node_modules/moment/locale/*.js 499 KiB 135 modules
modules by path ./resources/public/cljs-out/dev/ 422 KiB
  ./resources/public/cljs-out/dev/main.js 422 KiB [built] [code generated]
  ./resources/public/cljs-out/dev/ sync 160 bytes [built] [code generated]
./node_modules/moment/moment.js 170 KiB [built] [code generated]
./node_modules/moment/locale/ sync ^\.\/.*$ 3.21 KiB [optional] [built] [code generated]

WARNING in ./resources/public/cljs-out/dev/main.js 772:177-179
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./resources/public/cljs-out/dev/main.js 772:182-184
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./resources/public/cljs-out/dev/main.js 772:205-207
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

3 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

ERROR in ./resources/public/cljs-out/dev/main.js 57:95-111
Module not found: Error: Can't resolve 'react' in '/home/daniel/Workspace/Checkouts/fullstack-clj/resources/public/cljs-out/dev'
resolve 'react' in '/home/daniel/Workspace/Checkouts/fullstack-clj/resources/public/cljs-out/dev'
  Parsed request is a module
  using description file: /home/daniel/Workspace/Checkouts/fullstack-clj/package.json (relative path: ./resources/public/cljs-out/dev)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/daniel/Workspace/Checkouts/fullstack-clj/resources/public/cljs-out/dev/node_modules doesn't exist or is not a directory
      /home/daniel/Workspace/Checkouts/fullstack-clj/resources/public/cljs-out/node_modules doesn't exist or is not a directory
      /home/daniel/Workspace/Checkouts/fullstack-clj/resources/public/node_modules doesn't exist or is not a directory
      /home/daniel/Workspace/Checkouts/fullstack-clj/resources/node_modules doesn't exist or is not a directory
      looking for modules in /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules
        single file module
          using description file: /home/daniel/Workspace/Checkouts/fullstack-clj/package.json (relative path: ./node_modules/react)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules/react doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules/react.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules/react.json doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules/react.wasm doesn't exist
        /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules/react doesn't exist
      /home/daniel/Workspace/Checkouts/node_modules doesn't exist or is not a directory
      /home/daniel/Workspace/node_modules doesn't exist or is not a directory
      /home/daniel/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory

webpack 5.30.0 compiled with 1 error and 3 warnings in 6295 ms
 {:figwheel.main/error true, :cmd ["npx" "webpack" "--mode=production" "./resources/public/cljs-out/dev/main.js" "--output-path" "./resources/public/cljs-out/dev" "--output-filename" "main_bundle.js"], :exit-code 1, :stdout "assets by status 702 KiB [cached] 1 asset\nruntime modules 211 bytes 2 modules\nmodules by path ./node_modules/moment/locale/*.js 499 KiB 135 modules\nmodules by path ./resources/public/cljs-out/dev/ 422 KiB\n  ./resources/public/cljs-out/dev/main.js 422 KiB [built] [code generated]\n  ./resources/public/cljs-out/dev/ sync 160 bytes [built] [code generated]\n./node_modules/moment/moment.js 170 KiB [built] [code generated]\n./node_modules/moment/locale/ sync ^\\.\\/.*$ 3.21 KiB [optional] [built] [code generated]\n\nWARNING in ./resources/public/cljs-out/dev/main.js 772:177-179\nCritical dependency: require function is used in a way in which dependencies cannot be statically extracted\n\nWARNING in ./resources/public/cljs-out/dev/main.js 772:182-184\nCritical dependency: require function is used in a way in which dependencies cannot be statically extracted\n\nWARNING in ./resources/public/cljs-out/dev/main.js 772:205-207\nCritical dependency: require function is used in a way in which dependencies cannot be statically extracted\n\n3 warnings have detailed information that is not shown.\nUse 'stats.errorDetails: true' resp. '--stats-error-details' to show it.\n\nERROR in ./resources/public/cljs-out/dev/main.js 57:95-111\nModule not found: Error: Can't resolve 'react' in '/home/daniel/Workspace/Checkouts/fullstack-clj/resources/public/cljs-out/dev'\nresolve 'react' in '/home/daniel/Workspace/Checkouts/fullstack-clj/resources/public/cljs-out/dev'\n  Parsed request is a module\n  using description file: /home/daniel/Workspace/Checkouts/fullstack-clj/package.json (relative path: ./resources/public/cljs-out/dev)\n    Field 'browser' doesn't contain a valid alias configuration\n    resolve as module\n      /home/daniel/Workspace/Checkouts/fullstack-clj/resources/public/cljs-out/dev/node_modules doesn't exist or is not a directory\n      /home/daniel/Workspace/Checkouts/fullstack-clj/resources/public/cljs-out/node_modules doesn't exist or is not a directory\n      /home/daniel/Workspace/Checkouts/fullstack-clj/resources/public/node_modules doesn't exist or is not a directory\n      /home/daniel/Workspace/Checkouts/fullstack-clj/resources/node_modules doesn't exist or is not a directory\n      looking for modules in /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules\n        single file module\n          using description file: /home/daniel/Workspace/Checkouts/fullstack-clj/package.json (relative path: ./node_modules/react)\n            no extension\n              Field 'browser' doesn't contain a valid alias configuration\n              /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules/react doesn't exist\n            .js\n              Field 'browser' doesn't contain a valid alias configuration\n              /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules/react.js doesn't exist\n            .json\n              Field 'browser' doesn't contain a valid alias configuration\n              /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules/react.json doesn't exist\n            .wasm\n              Field 'browser' doesn't contain a valid alias configuration\n              /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules/react.wasm doesn't exist\n        /home/daniel/Workspace/Checkouts/fullstack-clj/node_modules/react doesn't exist\n      /home/daniel/Workspace/Checkouts/node_modules doesn't exist or is not a directory\n      /home/daniel/Workspace/node_modules doesn't exist or is not a directory\n      /home/daniel/node_modules doesn't exist or is not a directory\n      /home/node_modules doesn't exist or is not a directory\n      /node_modules doesn't exist or is not a directory\n\nwebpack 5.30.0 compiled with 1 error and 3 warnings in 6295 ms\n", :stderr ""}
	at figwheel.main$run_bundle_cmd_STAR_.invokeStatic(main.cljc:135)
	at figwheel.main$run_bundle_cmd_STAR_.invoke(main.cljc:123)
	at figwheel.main$run_bundle_cmd.invokeStatic(main.cljc:144)
	at figwheel.main$run_bundle_cmd.invoke(main.cljc:140)
	at figwheel.main$run_bundle_cmd.invokeStatic(main.cljc:141)
	at figwheel.main$run_bundle_cmd.invoke(main.cljc:140)
	at figwheel.main$wrap_with_bundling$fn__6156.doInvoke(main.cljc:155)
	at clojure.lang.RestFn.applyTo(RestFn.java:146)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at figwheel.main$wrap_with_build_hooks$fn__6179.doInvoke(main.cljc:209)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at figwheel.main$wrap_with_compiler_passes$fn__6182.doInvoke(main.cljc:218)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at figwheel.main$build.invokeStatic(main.cljc:1772)
	at figwheel.main$build.invoke(main.cljc:1768)
	at figwheel.main$default_compile$fn__8473.invoke(main.cljc:2193)
	at figwheel.main$default_compile.invokeStatic(main.cljc:2192)
	at figwheel.main$default_compile.invoke(main.cljc:2167)
	at figwheel.main$build_once_main_opt.invokeStatic(main.cljc:656)
	at figwheel.main$build_once_main_opt.invoke(main.cljc:655)
	at cljs.cli$main.invokeStatic(cli.clj:703)
	at cljs.cli$main.doInvoke(cli.clj:692)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at cljs.main$_main.invokeStatic(main.clj:65)
	at cljs.main$_main.doInvoke(main.clj:56)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at figwheel.main$_main$fn__8669.invoke(main.cljc:2553)
	at clojure.core$with_redefs_fn.invokeStatic(core.clj:7514)
	at clojure.core$with_redefs_fn.invoke(core.clj:7498)
	at figwheel.main$_main.invokeStatic(main.cljc:2551)
	at figwheel.main$_main.doInvoke(main.cljc:2529)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at clojure.lang.Var.invoke(Var.java:399)
	at user$eval140.invokeStatic(form-init15416168890662789767.clj:1)
	at user$eval140.invoke(form-init15416168890662789767.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	... 12 more
```

**Comment by danielmarreirosdeoliveira** [comment]
Ok, I think i figured that one out with https://github.com/danielmarreirosdeoliveira/fullstack-clj/commit/9fe90e1e9d65798846ced7f0e14c61571c5da076

I tried to set up everything from scratch via https://github.com/bhauman/figwheel-main-template. This time with the `+npm-bunde` option. I then saw that one has `react` excluded from the reagent dependencies and instead inserted into the `package.json` as dependency.
